# for details information, see at the bottom

name: Django coverage 

on:
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  coverage:

    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 100
      COVERAGE_TOTAL: 100

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install coverage

# For more details about the coverage, check the index.hml file in ./htmlcov directory
    - name: run coverage from unittest
      run: |
        coverage run --source='.' --rcfile=.coveragerc_ini manage.py test
        coverage html
        coverage report > ./htmlcov/coverage.txt
    - name: coverage
      id: coverage
      run: |
        echo ::set-output name=single-output-success::$(python -c 'from utils.coverage_parser import file_coverage_parser; file_coverage_parser()')
        echo ::set-output name=whole-output-success::$(python -c 'from utils.coverage_parser import whole_coverage_parser; whole_coverage_parser()')
        echo ::set-output name=output-table::$(cat htmlcov/index.html)
    - name: Coverage single fail - new issue
      if: ${{ steps.coverage.outputs.single-output-success != 'true' }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Python coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: ${{ steps.coverage.outputs.output-table }}

    - name: Coverage single fail - artifact html directory
      if: ${{ steps.coverage.outputs.single-output-success != 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov/

    - name: Coverage single fail - exit
      if: ${{ steps.coverage.outputs.single-output-success != 'true' }}
      run: |
        echo "coverage single fail ${{ steps.coverage.outputs.single-output-success }}"
        exit 1

    - name: Coverage total fail - new issue
      if: ${{ steps.coverage.outputs.whole-output-success != 'true' }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Python coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: ${{ steps.coverage.outputs.output-table }}

    - name: Coverage total fail - artifact html directory
      if: ${{ steps.coverage.outputs.whole-output-success != 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov/

    - name: Coverage total fail - exit
      if: ${{ steps.coverage.outputs.whole-output-success != 'true' }}
      run: |
        echo "cov total fail ${{ steps.coverage.outputs.whole-output-success }}"
        exit 1

    - name: Python coverage table
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ steps.coverage.outputs.output-table }}

    - name: Coverage - artifact html directory
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov/

# Freely inspired from github actions: alexanderdamiani/pytester-cov
