# for details information, see at the bottom

name: Django complete tests, coverage, and security check

on:
  push:

jobs:
  call-workflow-django-test:
    uses: xrochard/personal_portfolio/.github/workflows/django-test-reusable.yml@v1.3
  call-workflow-django-coverage:
    uses: xrochard/personal_portfolio/.github/workflows/django-coverage-reusable.yml@v1.11
  call-workflow-django-security:
    uses: xrochard/personal_portfolio/.github/workflows/django-security-reusable.yml@v1.1

# No comment
