# for details information, see at the bottom

name: Django tests reusable workflow

on:
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  django-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 parameterized
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run utils tests
      run: |
        python -m  unittest discover utils
    - name: Test a connection to Django (sanity check)
      run: python manage.py test core/
    - name: run apps unit and integration tests
      run: |
        # TODO reactivate blog tests 
        # python manage.py test blog/tests/
        python manage.py test portfolio/tests/

  post-django-ci:

    runs-on: ubuntu-latest

    needs: django-ci
    if: always() 
    steps:
    - name: CI tests failed - new issue
      if: ${{ needs.django-ci.result != 'success' }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: CI tests failure for the commit - ${{ github.event.head_commit.message }}
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: 

# List of the jobs:
#   - "django-ci" will install Python dependencies, run tests and lint with a single version of Python
#     For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#   - "post-django-ci" creates an issue if "django-test-reusable" failed 
#     (quite slow but it cannot be set in another workflow 
#      because outputs generated by a called workflow can't be accessed by the caller workflow and pass to another called workflow)
