# for details information, see at the bottom

name: Django security check

on:
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  security-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Scan Django settings for security issues
      id: check
      run: |
        python manage.py check --deploy --fail-level ERROR &> output.txt
    - id: results
      run: |
        OUTPUT=$(cat output.txt)
        FORMATTED=${OUTPUT//$'\n'/%0A}
        echo ::set-output name=file::**Django Security Check identified issues:** %0A$FORMATTED
    - name: Comment with output
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ steps.results.outputs.file }}

  post-django-security-check:

    runs-on: ubuntu-latest

    needs: security-check
    if: always() 
    steps:
    - name: CI tests failed - new issue
      if: ${{ needs.security-check.result != 'success' }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Security check failure for the commit - ${{ github.event.head_commit.message }}
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Check the comment associated with the commit

# List of the jobs:
#   - "security-check" runs a security check on Django
#     It is greatly inspired from victoriadrake/django-security-check@master (not used because I need to change the installed modules)
#   - "post-django-security-check" creates an issue if "security-check" failed
